//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SituationMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area_Table
    {
        public Area_Table()
        {
            this.Situation_Table = new HashSet<Situation_Table>();
        }
    
        public int AreaID { get; set; }
        public string AreaArName { get; set; }
        public string AreaEnName { get; set; }
        public Nullable<int> GovernorateID { get; set; }
    
        public virtual Governorate_Table Governorate_Table { get; set; }
        public virtual ICollection<Situation_Table> Situation_Table { get; set; }
    }
}
