//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SituationMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Key_concernTable
    {
        public Key_concernTable()
        {
            this.PersonInNeed_table = new HashSet<PersonInNeed_table>();
        }
    
        public int ID { get; set; }
        public string Key_concern { get; set; }
    
        public virtual ICollection<PersonInNeed_table> PersonInNeed_table { get; set; }
    }
}
