//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SituationMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipality_Table
    {
        public int MunicipalityID { get; set; }
        public string MunicipalityEnName { get; set; }
        public string MunicipalityArName { get; set; }
        public Nullable<int> GovernorateID { get; set; }
    
        public virtual Governorate_Table Governorate_Table { get; set; }
    }
}
