//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SituationMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonInNeed_table
    {
        public int ID { get; set; }
        public string Name_of_Person_In_Need { get; set; }
        public string Contact_Details { get; set; }
        public Nullable<int> KeyConcernID { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string ActionsTakenSoFar { get; set; }
        public string FollowUpRequired { get; set; }
        public Nullable<int> SituationID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Key_concernTable Key_concernTable { get; set; }
        public virtual Situation_Table Situation_Table { get; set; }
        public virtual Users_Table Users_Table { get; set; }
    }
}
