//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SituationMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionnaire_Table
    {
        public int QuestionnaireID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> SituationID { get; set; }
        public Nullable<System.DateTime> QuestionnaireDate { get; set; }
        public string EmployeeName { get; set; }
        public string CenterName { get; set; }
        public string EmployeeMail { get; set; }
        public string EmployeePhone { get; set; }
        public string PersonName { get; set; }
        public string PersonGEnder { get; set; }
        public string RoleInCommunity { get; set; }
        public string Place_of_origin { get; set; }
        public string PersonMobile { get; set; }
        public string CollectiveCenter { get; set; }
        public Nullable<int> Estimated_Number_Of_Individuals { get; set; }
        public Nullable<int> Estimated_Number_Of_Families { get; set; }
        public string Site_Description { get; set; }
        public string Question1_1 { get; set; }
        public string Question1_1_1 { get; set; }
        public bool Question1_2_1_Family_CommunityDisputes { get; set; }
        public bool Question_1_2_2NotEnoughFood { get; set; }
        public bool Question1_2_3NotEnoughPrivacy { get; set; }
        public bool Question1_2_4NotEnoughDrinking { get; set; }
        public bool Question1_2_5UnsafeHousing { get; set; }
        public bool Question1_2_6Overcrowding { get; set; }
        public bool Question1_2_7InsufficientBedding { get; set; }
        public bool Question1_2_8NotEnoughWater { get; set; }
        public bool Question1_2_9Not_enough_humanitarian_assistance { get; set; }
        public string Question1_2_9Text { get; set; }
        public bool Question1_2_10No_Access_to_essential_services { get; set; }
        public string Question1_2_10Text { get; set; }
        public bool Question1_2_11Other { get; set; }
        public string Question1_2_11Text { get; set; }
        public bool Question1_3_1Family_CommunityDisputes { get; set; }
        public bool Question1_3_2NotEnoughFood { get; set; }
        public bool Question1_3_3NotEnoughDrinking { get; set; }
        public bool Question1_3_4UnsafeHousing { get; set; }
        public bool Question1_3_5Overcrowding { get; set; }
        public bool Question1_3_5NotEnoughWater { get; set; }
        public bool Question1_3_6Not_enough_humanitarian_assistance { get; set; }
        public string Question1_3_6Text { get; set; }
        public bool Question1_3_7No_Access_to_essential_services { get; set; }
        public string Question1_3_7Text { get; set; }
        public bool Question1_3_8Other { get; set; }
        public string Question1_3_8Text { get; set; }
        public string Question1_4 { get; set; }
        public string Question1_4_1 { get; set; }
        public bool Question2_1_1Family_CommunityDisputes { get; set; }
        public bool Question2_1_2NotEnoughFood { get; set; }
        public bool Question2_1_3NotEnoughPrivacy { get; set; }
        public bool Question2_1_4NotDrinkingEnoughWater { get; set; }
        public bool Question2_1_5UnsafeHousing { get; set; }
        public bool Question2_1_6Overcrowding { get; set; }
        public bool Question2_1_7InsufficientBedding { get; set; }
        public bool Question2_1_8NotEnoughWater { get; set; }
        public bool Question2_1_9NotEnoughHumanitarianAssistance { get; set; }
        public string Question2_1_9Text { get; set; }
        public bool Question2_1_10NoAccessToEssentialServices { get; set; }
        public string Question2_1_10Text { get; set; }
        public bool Question2_1_11DistributionOfAssistanceExcludesChild_headedFamilies { get; set; }
        public bool Question2_1_12DistributionOfAssistanceExcludesWomen_headedFamilies { get; set; }
        public bool Question2_1_13LackOfSafeSpacesForWomenAndGirlsToGather { get; set; }
        public bool Question2_1_14LackOfSafeSpacesForChildrenToPlay { get; set; }
        public bool Question2_1_15LackOfAdequateLightingForToilets { get; set; }
        public bool Question2_1_16LackOfGenderSegregatedToilets { get; set; }
        public bool Question2_1_17LackOfGenderSegregatedBathingFacilities { get; set; }
        public bool Question2_1_18Other { get; set; }
        public string Question2_1_18text { get; set; }
        public string Question2_2 { get; set; }
        public string Question2_2_1 { get; set; }
        public string Question2_3 { get; set; }
        public string Question2_3_1 { get; set; }
        public string Question3_1 { get; set; }
        public Nullable<int> Question3_1Male { get; set; }
        public Nullable<int> Question3_1Femal { get; set; }
        public string Question3_2 { get; set; }
        public Nullable<int> Question3_2Male { get; set; }
        public Nullable<int> Question3_2Femal { get; set; }
        public string Question3_3 { get; set; }
        public Nullable<int> Question3_3Male { get; set; }
        public Nullable<int> Question3_3Femal { get; set; }
        public string Question3_4 { get; set; }
        public Nullable<int> Question3_4Male { get; set; }
        public Nullable<int> Question3_4Femal { get; set; }
        public string Question3_5 { get; set; }
        public Nullable<int> Question3_5Male { get; set; }
        public Nullable<int> Question3_5Femal { get; set; }
        public string Question3_6 { get; set; }
        public Nullable<int> Question3_6Male { get; set; }
        public Nullable<int> Question3_6Femal { get; set; }
        public string Question3_7 { get; set; }
        public Nullable<int> Question3_7Male { get; set; }
        public Nullable<int> Question3_7Femal { get; set; }
        public string Question3_8 { get; set; }
        public Nullable<int> Question3_8Male { get; set; }
        public Nullable<int> Question3_8Femal { get; set; }
        public string Question3_9 { get; set; }
        public Nullable<int> Question3_9Male { get; set; }
        public Nullable<int> Question3_9Femal { get; set; }
        public string Question3_10 { get; set; }
        public Nullable<int> Question3_10Male { get; set; }
        public Nullable<int> Question3_10Femal { get; set; }
        public string Question3_11 { get; set; }
        public Nullable<int> Question3_11Male { get; set; }
        public Nullable<int> Question3_11Femal { get; set; }
        public string Question3_12 { get; set; }
        public Nullable<int> Question3_12Male { get; set; }
        public Nullable<int> Question3_12Femal { get; set; }
        public string Question3_13 { get; set; }
        public Nullable<int> Question3_13Male { get; set; }
        public Nullable<int> Question3_13Femal { get; set; }
        public string Question3_14 { get; set; }
        public Nullable<int> Question3_14Male { get; set; }
        public Nullable<int> Question3_14Femal { get; set; }
        public string Question3_15 { get; set; }
        public Nullable<int> Question3_15Male { get; set; }
        public Nullable<int> Question3_15Femal { get; set; }
        public string Question3_16 { get; set; }
        public Nullable<int> Question3_16Male { get; set; }
        public Nullable<int> Question3_16Femal { get; set; }
        public string Question3_17 { get; set; }
        public Nullable<int> Question3_17Male { get; set; }
        public Nullable<int> Question3_17Femal { get; set; }
        public string Question3_18 { get; set; }
        public Nullable<int> Question3_18Male { get; set; }
        public Nullable<int> Question3_18Femal { get; set; }
        public string Question3_19 { get; set; }
        public string Question3_20 { get; set; }
        public string Question3_20Text { get; set; }
        public Nullable<int> Question3_20Male { get; set; }
        public Nullable<int> Question3_20Femal { get; set; }
        public bool Question4_1_1 { get; set; }
        public bool Question4_1_2 { get; set; }
        public bool Question4_1_3 { get; set; }
        public bool Question4_1_4 { get; set; }
        public bool Question4_1_5 { get; set; }
        public bool Question4_1_6 { get; set; }
        public bool Question4_1_7 { get; set; }
        public bool Question4_1_8 { get; set; }
        public bool Question4_1_9 { get; set; }
        public string Question4_1_9Text { get; set; }
        public bool Question4_1_10 { get; set; }
        public string Question_5 { get; set; }
    
        public virtual Situation_Table Situation_Table { get; set; }
        public virtual Users_Table Users_Table { get; set; }
    }
}
