//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SituationMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SituationUser_Table
    {
        public int ID { get; set; }
        public Nullable<int> SituationID { get; set; }
        public Nullable<int> UserID { get; set; }
        public bool Status { get; set; }
    
        public virtual Situation_Table Situation_Table { get; set; }
        public virtual Users_Table Users_Table { get; set; }
    }
}
