//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SituationMonitoring.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SituationMonitoringEntities : DbContext
    {
        public SituationMonitoringEntities()
            : base("name=SituationMonitoringEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Area_Table> Area_Table { get; set; }
        public DbSet<Governorate_Table> Governorate_Table { get; set; }
        public DbSet<Key_concernTable> Key_concernTable { get; set; }
        public DbSet<Municipality_Table> Municipality_Table { get; set; }
        public DbSet<PersonInNeed_table> PersonInNeed_table { get; set; }
        public DbSet<Questionnaire_Table> Questionnaire_Table { get; set; }
        public DbSet<Situation_Table> Situation_Table { get; set; }
        public DbSet<SituationUser_Table> SituationUser_Table { get; set; }
        public DbSet<Users_Table> Users_Table { get; set; }
    }
}
